---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: update packages
    apt:
      name: "*"
      state: latest
      update_cache: true

  - name: autoremove packages
    apt:
      autoremove: yes

  - name: autoclean packages
    apt:
      autoclean: yes

  - name: install core snap
    snap:
      name:
        - core
    when: ansible_facts['distribution'] == 'Debian'

  - name: install standard snaps
    snap:
      name:
        - steam
        - bitwarden
        - discord
        - telegram-desktop
        - zoom-client

  - name: install classic snaps
    snap:
      classic: yes
      name:
        - powershell
        - julia
        - code
        - nvim
        - helix
